---
version: '3'
services:
  postgresql:
    image: postgres:12
    container_name: ktor_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
